{{- if .Values.istio.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "publisher-demo.fullname" . }}-tls
  # Must be in gateway namespace for Istio to access the secret.
  namespace: {{ .Values.istio.gatewayNamespace }}
  labels:
    {{- include "publisher-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
spec:
  secretName: {{ include "publisher-demo.fullname" . }}-tls
  issuerRef:
    name: {{ .Values.istio.certificate.issuerName }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.istio.host }}
{{- end }}
