apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "publisher-demo.fullname" . }}
  labels: {{- include "publisher-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "publisher-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "publisher-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: publisher-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.externalSecret.enabled }}
            {{- range $key, $_ := .Values.externalSecret.data }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "publisher-demo.fullname" $ }}-secrets
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 30
            periodSeconds: 30
          resources: {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
