{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "publisher-demo.fullname" . }}-secrets
  labels: {{- include "publisher-demo.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRefName }}
    kind: {{ .Values.externalSecret.secretStoreRefKind }}
  target:
    name: {{ include "publisher-demo.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range $key, $cfg := .Values.externalSecret.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $cfg.remoteKey }}
        property: {{ $cfg.property }}
    {{- end }}
{{- end }}
