{{- if .Values.istio.virtualService.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "openaire.fullname" . }}-vs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "openaire.labels" . | nindent 4 }}
    app.kubernetes.io/component: virtualservice
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - {{ .Values.istio.gatewayNamespace }}/{{ include "openaire.fullname" . }}-gateway
  http:
    - name: openaire-route
      match:
        - uri:
            prefix: {{ .Values.istio.path }}
      route:
        - destination:
            host: {{ include "openaire.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
      {{- with .Values.istio.virtualService.timeout }}
      timeout: {{ . }}
      {{- end }}
      {{- with .Values.istio.virtualService.retries }}
      retries:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
