// JSONL event parser for Claude Code `--output-format stream-json`.
// Replaces lib/tool-result-extractors.ts — works on raw stdout lines instead of SDK hooks.

import type { ChartData } from '@/types/chart';

/** Keys that contain research products worth collecting */
const PAPER_KEYS = ['results', 'datasets', 'publications', 'papers', 'outputs'] as const;

export interface ParsedEvent {
  type: 'text' | 'tool_start' | 'tool_result' | 'papers' | 'chart' | 'session_init' | 'turn_result' | 'unknown';
  // text
  text?: string;
  // tool_start
  toolUseId?: string;
  toolName?: string;
  toolInput?: any;
  // tool_result
  toolResultId?: string;
  isError?: boolean;
  toolResultContent?: string;
  // papers
  papers?: any[];
  // chart
  chart?: ChartData;
  // session_init
  sessionId?: string;
  // turn_result
  usage?: { input_tokens: number; output_tokens: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number };
  // raw — the whole parsed line
  raw?: any;
}

/**
 * Parse a single JSONL line from Claude Code stdout into a structured event.
 */
export function parseStreamEvent(line: string): ParsedEvent | null {
  const trimmed = line.trim();
  if (!trimmed) return null;

  let obj: any;
  try {
    obj = JSON.parse(trimmed);
  } catch {
    return null;
  }

  // System init — contains session_id
  if (obj.type === 'system' && obj.subtype === 'init') {
    return { type: 'session_init', sessionId: obj.session_id, raw: obj };
  }

  // Assistant message — contains text blocks and tool_use blocks
  if (obj.type === 'assistant') {
    const content = obj.message?.content;
    const events: ParsedEvent[] = [];

    if (typeof content === 'string') {
      return { type: 'text', text: content, raw: obj };
    }

    if (Array.isArray(content)) {
      // We return the first meaningful event; caller should iterate content blocks
      // But since we return one event per line, we return a compound event
      // Better: return the raw and let the route handler iterate
      return { type: 'unknown', raw: obj };
    }

    return { type: 'unknown', raw: obj };
  }

  // User message — tool results (auto-generated by Claude Code after tool execution)
  if (obj.type === 'user') {
    return { type: 'unknown', raw: obj };
  }

  // Result — marks end of turn
  if (obj.type === 'result') {
    return {
      type: 'turn_result',
      usage: obj.usage || undefined,
      raw: obj,
    };
  }

  return { type: 'unknown', raw: obj };
}

/**
 * Parse tool result content string into a JS object.
 */
function parseToolResultContent(content: unknown): any | null {
  if (!content) return null;

  if (typeof content === 'string') {
    try { return JSON.parse(content); } catch { return null; }
  }

  if (Array.isArray(content)) {
    const textBlock = content.find((b: any) => b.type === 'text');
    if (textBlock?.text) {
      const text = textBlock.text.trim();
      if (!text.startsWith('{') && !text.startsWith('[')) return null;
      try { return JSON.parse(text); } catch { return null; }
    }
    return null;
  }

  if (typeof content === 'object') return content;
  return null;
}

/**
 * Extract research papers/products from a tool result content block.
 */
export function extractPapersFromToolResult(content: unknown): any[] {
  const toolData = parseToolResultContent(content);
  if (!toolData) return [];

  // Check for successful response with data
  if (toolData.success && toolData.data) {
    const data = toolData.data;

    // Check all known paper-like array keys
    for (const key of PAPER_KEYS) {
      if (Array.isArray(data[key]) && data[key].length > 0) {
        return data[key];
      }
    }

    // Single research product
    if (data.id && data.title) {
      return [data];
    }

    // Citation network nodes → extract as papers
    if (data.nodes && Array.isArray(data.edges) && !data.centerAuthor && !data.metadata?.totalAuthors) {
      return data.nodes.map((node: any) => ({
        id: node.id,
        title: node.title,
        type: node.type || 'publication',
        publicationDate: `${node.year}-01-01`,
        citations: node.citations || 0,
        openAccess: node.openAccess,
        authors: [],
      }));
    }
  }

  return [];
}

/**
 * Extract chart/visualization data from a tool result content block.
 */
export function extractChartFromToolResult(content: unknown): ChartData | null {
  const toolData = parseToolResultContent(content);
  if (!toolData?.visualization) return null;
  return toolData.visualization;
}

/**
 * Extract markdown tables from text and convert to ChartData objects.
 * Returns the tables as chart data and the text with tables removed.
 */
export function extractTablesFromMarkdown(text: string): { charts: ChartData[]; cleanedText: string } {
  const charts: ChartData[] = [];

  // Match GFM tables: header row, separator row, data rows
  const tableRegex = /(?:^|\n)((?:\|.+\|[ \t]*\n)\|[\s:|-]+\|[ \t]*\n(?:\|.+\|[ \t]*\n?)+)/g;

  const cleanedText = text.replace(tableRegex, (match, table: string) => {
    const lines = table.trim().split('\n').map(l => l.trim()).filter(Boolean);
    if (lines.length < 3) return match; // need header + separator + at least 1 row

    // Parse header
    const headerCells = lines[0].split('|').map(c => c.trim()).filter(Boolean);
    // Skip separator (lines[1])
    // Parse alignment from separator
    const sepCells = lines[1].split('|').map(c => c.trim()).filter(Boolean);
    const aligns = sepCells.map(cell => {
      if (cell.startsWith(':') && cell.endsWith(':')) return 'center' as const;
      if (cell.endsWith(':')) return 'right' as const;
      return 'left' as const;
    });

    const columns = headerCells.map((label, i) => ({
      key: `col${i}`,
      label,
      align: aligns[i] || ('left' as const),
    }));

    // Parse data rows
    const rows = lines.slice(2).map(line => {
      const cells = line.split('|').map(c => c.trim()).filter(Boolean);
      const row: Record<string, string> = {};
      columns.forEach((col, i) => {
        row[col.key] = cells[i] || '';
      });
      return row;
    });

    if (rows.length === 0) return match;

    charts.push({
      chartType: 'table',
      config: {
        title: 'Results',
        description: `${rows.length} rows`,
      },
      data: rows,
      chartConfig: {},
      tableColumns: columns,
    });

    return '\n\n**See table in visualization panel →**\n\n';
  });

  return { charts, cleanedText: cleanedText.trim() };
}

/**
 * Check if tool result contains a citation network (for metric tracking).
 */
export function isCitationNetwork(content: unknown): boolean {
  const toolData = parseToolResultContent(content);
  if (!toolData?.success || !toolData?.data) return false;
  const data = toolData.data;
  return !!(data.nodes && Array.isArray(data.edges) && !data.centerAuthor && !data.metadata?.totalAuthors);
}
