apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: publisher-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/alias3/datastreaming.git
    targetRevision: HEAD
    path: datastreaming-demos/publisher-demo/helm/publisher-demo-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: publisher-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
